import { JSDOM, VirtualConsole } from "jsdom";
import vm from "node:vm";
import type { SandboxRunner } from "../../core/ports.js";

/**
 * Default in-process sandbox: build a jsdom Document from the page HTML, then
 * run the LLM-generated `extract(document)` inside jsdom's VM context.
 *
 * Isolation provided:
 *  - `runScripts: "outside-only"` — the PAGE's own scripts never execute;
 *    only our extractor runs.
 *  - JSON boundary — the return value is JSON.stringify'd inside the context,
 *    so a DOM node / circular ref / non-serializable return throws instead of
 *    leaking a live object across the realm.
 *  - Hard wall-clock timeout via Promise.race.
 *
 * NOTE: node's `vm` is NOT a security boundary against deliberately malicious
 * code (it can escape). It is sufficient here because the code is generated by
 * our own trusted LLM call, not by an attacker. For untrusted code, implement
 * SandboxRunner with isolated-vm or an external jail — the port makes that a
 * drop-in swap.
 */
export const inProcessSandbox: SandboxRunner = {
  async run(job): Promise<unknown> {
    const { code, html, url, timeoutMs = 15_000 } = job;

    const dom = new JSDOM(html, {
      url: url || "https://example.invalid/",
      runScripts: "outside-only",
      pretendToBeVisual: true,
      virtualConsole: new VirtualConsole(),
    });

    // jsdom lacks innerText (needs layout); models reach for it constantly.
    const proto = dom.window.HTMLElement.prototype;
    if (!Object.getOwnPropertyDescriptor(proto, "innerText")) {
      Object.defineProperty(proto, "innerText", {
        get(this: HTMLElement) {
          return this.textContent;
        },
        set(this: HTMLElement, value: unknown) {
          this.textContent = value == null ? "" : String(value);
        },
        configurable: true,
      });
    }

    const context = dom.getInternalVMContext();
    const wrapped =
      "(async () => {\n" +
      code +
      "\n  const __value = await extract(document);\n" +
      "  return JSON.stringify(__value === undefined ? null : __value);\n" +
      "})()";

    let exec: Promise<unknown>;
    try {
      // The `timeout` option caps the SYNCHRONOUS portion — this is what kills
      // CPU-bound infinite loops (a Promise race can't, since a sync loop never
      // yields the event loop). Our extractors are essentially synchronous DOM
      // reads, so this covers the real runaway risk.
      exec = new vm.Script(wrapped).runInContext(context, {
        timeout: timeoutMs,
      }) as Promise<unknown>;
    } catch (err) {
      dom.window.close();
      const msg = (err as Error).message;
      if (/timed out/i.test(msg)) throw new Error(`extractor timed out after ${timeoutMs}ms`);
      throw new Error(`extractor failed to compile/run: ${msg}`);
    }

    try {
      const json = await withTimeout(exec, timeoutMs);
      return JSON.parse(typeof json === "string" ? json : "null");
    } finally {
      dom.window.close();
    }
  },
};

function withTimeout<T>(p: Promise<T>, ms: number): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    const t = setTimeout(
      () => reject(new Error(`extractor timed out after ${ms}ms`)),
      ms,
    );
    p.then(
      (v) => {
        clearTimeout(t);
        resolve(v);
      },
      (e) => {
        clearTimeout(t);
        reject(e);
      },
    );
  });
}
